version: 2.1 
orbs:
  aws-ecr: circleci/aws-ecr@0.0.10
  aws-ecs: circleci/aws-ecs@0.0.8
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
      - aws-ecr/build_and_push_image:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
            # branches:
            #   only: main
          account-url: ACCOUNT_URL
          repo: nacomer-react
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: AWS_DEFAULT_REGION
          family: nacomer-service
          cluster-name: nacomer-cluster
          container-image-name-updates: "container=nacomer-service,tag=${CIRCLE_SHA1}"
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: start
          command: echo "ci start"
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: install-yarn
          command: yarn
          paths:
            - ./node_modules
      - run:
          name: build
          command: |
            export CI=false
            yarn build
            export CI=true