version: 2.1 
orbs:
  aws-ecr: circleci/aws-ecr@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "988773502035.dkr.ecr.ap-northeast-1.amazonaws.com"
          repo: "nacomer-react"
          region: "ap-northeast-1"
          tag: "${CIRCLE_SHA1}"
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: start
          command: echo "ci start"
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: install-yarn
          command: yarn
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: echo "test"
      - run:
          name: deploy
          command: echo "deploy"
