version: 2.1 
jobs:
  build:
    docker: 
      - image: circleci/node:10.16.3 
    steps:
      - checkout 
      - run:
          name: start
          command: echo "ci start"
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-yarn
          command: yarn 
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test
      - run:
          name: deploy
          command: echo "deploy"